<?php
define("_SIGNUP2", "SIGN UP SECTION");
define("_SIGNUP", "SIGN UP");
define("_LOGIN", "LOGIN");
define("_LOGOUT","Logout");
define("_SEARCH","Search Topic");
define("_SEARCHED","searched");
define("_TITLEE","GO BACK");
define("_NOTHING","NOTHING FOUND");
define("_EXITMODE","Exit Edit Mode");
define("_USER", "Username");
define("_USERNAME", "E-mail/Username");
define("_PASSWORD1", "Password");
define("_PASSWORD2", "Retype Password");
define("_PASSWORD3", "Current Password");
define("_EMAIL", "Email");
define("_ADDRESS", "Address");
define("_CONNECT2", "LOG IN SECTION"); 
define("_FORGOT", "FORGOT PASSWORD?");
define("_REPLIES","Number of Replies");
define("_CONNECT", "LOG IN"); 
define("_RIGHTS","All Rights Reserved.");
define("_CREATED","Powered by ");
define("_WELCOME", "Welcome"); 
define("_ACCOUNT","Still not a member?");
define("_LANGUAGE","Select Language:");
define("_HOME","HOME");
define("_MEMBER","Create your free account for posting different topics or reply on topics!");
define("_CREATE","Become a member!");
define("_MODE","DARK");
define("_MODE2","MODE");
define("_REPLYED","REPLYED");
define("_ACCOUNT2","Check your Account!");
define("_DESC","In this section, you can change your profile settings!");
define("_ACC","Access Your Profile");
define("_ACCC","ACCOUNT");
define("_CATEG","CATEGORIES");
define("_PRF","PROFILE");
define("_ARCHIVED","ARCHIVED TOPICS");
define("_ABOUT","FORUM PAGES");
define("_WELCAD","welcome admin");
define("_WELCUS","welcome user");
define("_WELCST","welcome stranger");
define("_OR","or");
define("_ADDTOP","ADD TOPIC");
define("_TOPDESC","TOPIC DESCRIPTION...");
define("_TOPTITLE","TOPIC TITLE");
define("_ADDCATEG","ADD CATEGORY");
define("_CATDESC","CATEGORY DESCRIPTION...");
define("_CATTITLE","CATEGORY TITLE");
define("_ADDSUBCAT","ADD SUBCATEGORY");
define("_SUBDESC","SUBCATEGORY DESCRIPTION...");
define("_SUBTITLE","SUBCATEGORY TITLE");
define("_BEGIN","Beginner");
define("_ADVANCED","Advanced");
define("_ACTIVE","Active User");
define("_HELPER","Helper");
define("_EXPERT","Expert User");
define("_ABOUTU","Write something about you!");
define("_REPLY","Reply");
define("_RATIO","Upload a photo with aspect ratio 1:1!");
define("_REC","RECOVER");
define("_NOUSER","E-mail/Username doesn't EXIST!");
define("_RECCODEERR","WRONG SECURITY CODE!");
define("_PASSNEW","New PASSWORD");
define("_RECC","RECOVER PASSWORD SECTION");
define("_RECOVER","Code Recover Password");
define("_ORLOGIN","OR LOG IN INTO YOUR ACCOUNT:");
define("_EXIST","This Username is Already Taken!");
define("_EXIST2","This Email is Already Used for Another Account!");
define("_ERRPASS","Passwords doesn't match!");
define("_USERSP","Don't use Spaces in Username!");
define("_USERWRONG","Wrong Username/E-mail");
define("_PASSWRONG","Wrong PASSWORD");
define("_DATE","Created on:  ");
define("_DATE2","MEMBER FROM");
define("_USR","Created by ");
define("_SBCT","subcategories");
define("_TOP","topics");
define("_ARCH","Archive");
define("_ARC","archived ");
define("_SUCCES","CHANGES SAVED");
define("_VIEWS","Number of Views");
define("_TOPICS","Number of Topics");
define("_SUBCAT","Number of Subcategories");
define("_HAPPY","Happy Birthday, ");
define("_UPDATE","Update Profile");
define("_FILLED","This profile doesn't have a description!");
define("_EDIT","EDIT PROFILE");
define("_ABOUTU2","EDIT BIOGRAPHY");
define("_UPLOAD","UPLOAD PHOTO");
define("_NAME","Type your real name!");
define("_ADD","Add profile picture");
define("_UPDATE2","EDIT REAL NAME");
define("_UPDATE3","EDIT GENDER");
define("_UPDATE4","EDIT DATE");
define("_UPDATE5","EDIT PASSWORD");
define("_SELECT","SELECT GENDER");
define("_WRONGID","Write your full name!");
define("_MALE","MALE");
define("_NEUTRAL","NEUTRAL");
define("_FEMALE","FEMALE");
define("_EDIT2","EDIT PASSWORD");
define("_SUCCESPASS","PASSWORD CHANGED SUCCESFSULLY");
?>