<?php
define("_SIGNUP2", "ZONA DE INREGISTRARE");
define("_SIGNUP", "INREGISTRARE");
define("_LOGIN", "LOGARE");
define("_LOGOUT","Iesire");
define("_EXITMODE","Iesire Editare");
define("_USER", "Nume Utilizator");
define("_SEARCH","Cauta Topic");
define("_SEARCHED","cautate");
define("_TITLEE","MERGI INAPOI");
define("_NOTHING","NIMIC GASIT");
define("_USERNAME", "E-mail/Nume Utilizator");
define("_FORGOT", "Ai uitat parola?");
define("_PASSWORD1", "Parola");
define("_PASSWORD2", "Rescrie Parola");
define("_PASSWORD3", "Parola Actuala");
define("_EMAIL", "Email");
define("_ADDRESS", "Adresa");
define("_CONNECT2", "ZONA CONECTARE"); 
define("_CONNECT", "CONECTARE"); 
define("_WELCOME", "Bun Venit"); 
define("_ACCOUNT","Nu esti inca membru?");
define("_LANGUAGE","Alege Limba:");
define("_HOME","ACASA");
define("_MEMBER","Creeaza-ti propriul cont gratuit pentru a posta diferite topicuri sau a raspunde la alte topicuri!");
define("_CREATE","Inregistreaza-te Acum!");
define("_MODE","MOD");
define("_MODE2","INTUNECAT");
define("_REPLYED","RASPUNS");
define("_ACCOUNT2","Verifica-ti contul!");
define("_DESC","In aceasta sectiune, puteti modifica setarile contului!");
define("_ACC","Acceseaza-ti Profilul");
define("_ACCC","CONT");
define("_CATEG","CATEGORII");
define("_PRF","PROFIL");
define("_ARCHIVED","TOPICURI ARHIVATE");
define("_ABOUT","PAGINI FORUM");
define("_OR","sau");
define("_BEGIN","Incepator");
define("_ADVANCED","Avansat");
define("_ACTIVE","Utilizator Activ");
define("_HELPER","Ajutor");
define("_EXPERT","Utilizator Expert");
define("_ABOUTU","Scrie ceva despre tine!");
define("_REPLY","Raspunde");
define("_RATIO","Adauga o poza cu aspect ratio de 1:1");
define("_REC","RECUPEREAZA");
define("_NOUSER","E-mail-ul/Utilizatorul nu Exista!");
define("_RECCODEERR","COD DE SECURITATE GRESIT!");
define("_PASSNEW","Parola Noua");
define("_RECC","ZONA RECUPERARE PAROLA");
define("_RECOVER","Cod Recuperare Parola");
define("_ORLOGIN","sau conecteaza-te la contul tau:");
define("_EXIST","Acest Utilizator este deja utilizat!");
define("_EXIST2","Acest Email este deja utilizat!");
define("_ERRPASS","Parolele nu se potrivesc!");
define("_USERSP","Nu folosi spatii in Utilizator");
define("_USERWRONG","Utilizator/E-mail Gresit");
define("_PASSWRONG","Parola Gresita");
define("_DATE","Creat la:  ");
define("_DATE2","Membru din: ");
define("_USR","Creat de: ");
define("_SBCT","Subcategorii");
define("_TOP","Topicuri");
define("_ARCH","Arhiveaza");
define("_ARC","arhivate");
define("_REPLIES","Numar Raspunsuri");
define("_SUCCES","Modificari Salvate");
define("_RIGHTS","Toate drepturile rezervate.");
define("_CREATED","Creat de ");
define("_VIEWS","Numar de Vizualizari");
define("_TOPICS","Numar Topicuri");
define("_SUBCAT","Numar Subcategorii");
define("_HAPPY","La Multi Ani, ");
define("_UPDATE","Updateaza Profilul");
define("_FILLED","Acest profil nu are o descriere!");
define("_EDIT","MODIFICA DATE");
define("_ABOUTU2","EDITEAZA DESCRIERE");
define("_UPLOAD","SHIMBA POZA");
define("_NAME","Scrie-ti numele real!");
define("_ADD","ADAUGA POZA!");
define("_UPDATE2","EDITEAZA NUME REAL");
define("_UPDATE3","EDITEAZA GEN");
define("_UPDATE4","EDITEAZA DATA");
define("_UPDATE5","EDITEAZA PAROLA");
define("_SELECT","ALEGE GENUL");
define("_WRONGID","Scrie-ti numele complet!");
define("_MALE","MASCULIN");
define("_NEUTRAL","NEUTRU");
define("_FEMALE","FEMEIE");
define("_EDIT2","EDITEAZA PAROLA");
define("_SUCCESPASS","PAROLA SCHIMBATA CU SUCCES");
define("_WELCAD","bun venit admin");
define("_WELCUS","bun venit utilizatorule");
define("_WELCST","bun venit strainule");
define("_ADDTOP","ADAUGA TOPIC");
define("_TOPDESC","DESCRIERE TOPIC...");
define("_TOPTITLE","TITLU TOPIC");
define("_ADDCATEG","ADAUGA CATEGORIE");
define("_CATDESC","DESCRIERE CATEGORIE...");
define("_CATTITLE","TITLU CATEGORIE");
define("_ADDSUBCAT","ADAUGA SUBCATEGORIE");
define("_SUBDESC","DESCRIERE SUBCATEGORIE...");
define("_SUBTITLE","TITLU SUBCATEGORIE");
?>